server:
  host: 0.0.0.0
  port: 8000
database:
  url: postgresql://user:password@localhost:5432/proobbby_panel
jwt:
  secret_key: your_jwt_secret_key_here
node:
  websocket_url: ws://localhost:8080
backup:
  retention: 5
  backup_path: ./backups
